// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/laidbackware/harbor-cli/client/preheat"
	"github.com/laidbackware/harbor-cli/models"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationPreheatCreateInstanceCmd returns a cmd to handle operation createInstance
func makeOperationPreheatCreateInstanceCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "CreateInstance",
		Short: `Create p2p provider instances`,
		RunE:  runOperationPreheatCreateInstance,
	}

	if err := registerOperationPreheatCreateInstanceParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationPreheatCreateInstance uses cmd flags to call endpoint api
func runOperationPreheatCreateInstance(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := preheat.NewCreateInstanceParams()
	if err, _ := retrieveOperationPreheatCreateInstanceXRequestIDFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationPreheatCreateInstanceInstanceFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationPreheatCreateInstanceResult(appCli.Preheat.CreateInstance(params, nil))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationPreheatCreateInstanceParamFlags registers all flags needed to fill params
func registerOperationPreheatCreateInstanceParamFlags(cmd *cobra.Command) error {
	if err := registerOperationPreheatCreateInstanceXRequestIDParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationPreheatCreateInstanceInstanceParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationPreheatCreateInstanceXRequestIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	xRequestIdDescription := `An unique ID for the request`

	var xRequestIdFlagName string
	if cmdPrefix == "" {
		xRequestIdFlagName = "X-Request-Id"
	} else {
		xRequestIdFlagName = fmt.Sprintf("%v.X-Request-Id", cmdPrefix)
	}

	var xRequestIdFlagDefault string

	_ = cmd.PersistentFlags().String(xRequestIdFlagName, xRequestIdFlagDefault, xRequestIdDescription)

	return nil
}
func registerOperationPreheatCreateInstanceInstanceParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	var instanceFlagName string
	if cmdPrefix == "" {
		instanceFlagName = "instance"
	} else {
		instanceFlagName = fmt.Sprintf("%v.instance", cmdPrefix)
	}

	_ = cmd.PersistentFlags().String(instanceFlagName, "", "Optional json string for [instance]. The JSON object of instance.")

	// add flags for body
	if err := registerModelInstanceFlags(0, "instance", cmd); err != nil {
		return err
	}

	return nil
}

func retrieveOperationPreheatCreateInstanceXRequestIDFlag(m *preheat.CreateInstanceParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("X-Request-Id") {

		var xRequestIdFlagName string
		if cmdPrefix == "" {
			xRequestIdFlagName = "X-Request-Id"
		} else {
			xRequestIdFlagName = fmt.Sprintf("%v.X-Request-Id", cmdPrefix)
		}

		xRequestIdFlagValue, err := cmd.Flags().GetString(xRequestIdFlagName)
		if err != nil {
			return err, false
		}
		m.XRequestID = &xRequestIdFlagValue

	}
	return nil, retAdded
}
func retrieveOperationPreheatCreateInstanceInstanceFlag(m *preheat.CreateInstanceParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("instance") {
		// Read instance string from cmd and unmarshal
		instanceValueStr, err := cmd.Flags().GetString("instance")
		if err != nil {
			return err, false
		}

		instanceValue := models.Instance{}
		if err := json.Unmarshal([]byte(instanceValueStr), &instanceValue); err != nil {
			return fmt.Errorf("cannot unmarshal instance string in models.Instance: %v", err), false
		}
		m.Instance = &instanceValue
	}
	instanceValueModel := m.Instance
	if swag.IsZero(instanceValueModel) {
		instanceValueModel = &models.Instance{}
	}
	err, added := retrieveModelInstanceFlags(0, instanceValueModel, "instance", cmd)
	if err != nil {
		return err, false
	}
	if added {
		m.Instance = instanceValueModel
	}
	if dryRun && debug {

		instanceValueDebugBytes, err := json.Marshal(m.Instance)
		if err != nil {
			return err, false
		}
		logDebugf("Instance dry-run payload: %v", string(instanceValueDebugBytes))
	}
	retAdded = retAdded || added

	return nil, retAdded
}

// parseOperationPreheatCreateInstanceResult parses request result and return the string content
func parseOperationPreheatCreateInstanceResult(resp0 *preheat.CreateInstanceCreated, respErr error) (string, error) {
	if respErr != nil {

		// Non schema case: warning createInstanceCreated is not supported

		var iResp1 interface{} = respErr
		resp1, ok := iResp1.(*preheat.CreateInstanceBadRequest)
		if ok {
			if !swag.IsZero(resp1) && !swag.IsZero(resp1.Payload) {
				msgStr, err := json.Marshal(resp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp2 interface{} = respErr
		resp2, ok := iResp2.(*preheat.CreateInstanceUnauthorized)
		if ok {
			if !swag.IsZero(resp2) && !swag.IsZero(resp2.Payload) {
				msgStr, err := json.Marshal(resp2.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp3 interface{} = respErr
		resp3, ok := iResp3.(*preheat.CreateInstanceForbidden)
		if ok {
			if !swag.IsZero(resp3) && !swag.IsZero(resp3.Payload) {
				msgStr, err := json.Marshal(resp3.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp4 interface{} = respErr
		resp4, ok := iResp4.(*preheat.CreateInstanceNotFound)
		if ok {
			if !swag.IsZero(resp4) && !swag.IsZero(resp4.Payload) {
				msgStr, err := json.Marshal(resp4.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp5 interface{} = respErr
		resp5, ok := iResp5.(*preheat.CreateInstanceConflict)
		if ok {
			if !swag.IsZero(resp5) && !swag.IsZero(resp5.Payload) {
				msgStr, err := json.Marshal(resp5.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp6 interface{} = respErr
		resp6, ok := iResp6.(*preheat.CreateInstanceInternalServerError)
		if ok {
			if !swag.IsZero(resp6) && !swag.IsZero(resp6.Payload) {
				msgStr, err := json.Marshal(resp6.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	// warning: non schema response createInstanceCreated is not supported by go-swagger cli yet.

	return "", nil
}
