// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/laidbackware/harbor-cli/client/immutable"
	"github.com/laidbackware/harbor-cli/models"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationImmutableCreateImmuRuleCmd returns a cmd to handle operation createImmuRule
func makeOperationImmutableCreateImmuRuleCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use: "CreateImmuRule",
		Short: `This endpoint add an immutable tag rule to the project
`,
		RunE: runOperationImmutableCreateImmuRule,
	}

	if err := registerOperationImmutableCreateImmuRuleParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationImmutableCreateImmuRule uses cmd flags to call endpoint api
func runOperationImmutableCreateImmuRule(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := immutable.NewCreateImmuRuleParams()
	if err, _ := retrieveOperationImmutableCreateImmuRuleImmutableRuleFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationImmutableCreateImmuRuleXIsResourceNameFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationImmutableCreateImmuRuleXRequestIDFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationImmutableCreateImmuRuleProjectNameOrIDFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationImmutableCreateImmuRuleResult(appCli.Immutable.CreateImmuRule(params, nil))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationImmutableCreateImmuRuleParamFlags registers all flags needed to fill params
func registerOperationImmutableCreateImmuRuleParamFlags(cmd *cobra.Command) error {
	if err := registerOperationImmutableCreateImmuRuleImmutableRuleParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationImmutableCreateImmuRuleXIsResourceNameParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationImmutableCreateImmuRuleXRequestIDParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationImmutableCreateImmuRuleProjectNameOrIDParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationImmutableCreateImmuRuleImmutableRuleParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	var immutableRuleFlagName string
	if cmdPrefix == "" {
		immutableRuleFlagName = "ImmutableRule"
	} else {
		immutableRuleFlagName = fmt.Sprintf("%v.ImmutableRule", cmdPrefix)
	}

	_ = cmd.PersistentFlags().String(immutableRuleFlagName, "", "Optional json string for [ImmutableRule]. ")

	// add flags for body
	if err := registerModelImmutableRuleFlags(0, "immutableRule", cmd); err != nil {
		return err
	}

	return nil
}
func registerOperationImmutableCreateImmuRuleXIsResourceNameParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	xIsResourceNameDescription := `The flag to indicate whether the parameter which supports both name and id in the path is the name of the resource. When the X-Is-Resource-Name is false and the parameter can be converted to an integer, the parameter will be as an id, otherwise, it will be as a name.`

	var xIsResourceNameFlagName string
	if cmdPrefix == "" {
		xIsResourceNameFlagName = "X-Is-Resource-Name"
	} else {
		xIsResourceNameFlagName = fmt.Sprintf("%v.X-Is-Resource-Name", cmdPrefix)
	}

	var xIsResourceNameFlagDefault bool

	_ = cmd.PersistentFlags().Bool(xIsResourceNameFlagName, xIsResourceNameFlagDefault, xIsResourceNameDescription)

	return nil
}
func registerOperationImmutableCreateImmuRuleXRequestIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	xRequestIdDescription := `An unique ID for the request`

	var xRequestIdFlagName string
	if cmdPrefix == "" {
		xRequestIdFlagName = "X-Request-Id"
	} else {
		xRequestIdFlagName = fmt.Sprintf("%v.X-Request-Id", cmdPrefix)
	}

	var xRequestIdFlagDefault string

	_ = cmd.PersistentFlags().String(xRequestIdFlagName, xRequestIdFlagDefault, xRequestIdDescription)

	return nil
}
func registerOperationImmutableCreateImmuRuleProjectNameOrIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	projectNameOrIdDescription := `Required. The name or id of the project`

	var projectNameOrIdFlagName string
	if cmdPrefix == "" {
		projectNameOrIdFlagName = "project_name_or_id"
	} else {
		projectNameOrIdFlagName = fmt.Sprintf("%v.project_name_or_id", cmdPrefix)
	}

	var projectNameOrIdFlagDefault string

	_ = cmd.PersistentFlags().String(projectNameOrIdFlagName, projectNameOrIdFlagDefault, projectNameOrIdDescription)

	return nil
}

func retrieveOperationImmutableCreateImmuRuleImmutableRuleFlag(m *immutable.CreateImmuRuleParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("ImmutableRule") {
		// Read ImmutableRule string from cmd and unmarshal
		immutableRuleValueStr, err := cmd.Flags().GetString("ImmutableRule")
		if err != nil {
			return err, false
		}

		immutableRuleValue := models.ImmutableRule{}
		if err := json.Unmarshal([]byte(immutableRuleValueStr), &immutableRuleValue); err != nil {
			return fmt.Errorf("cannot unmarshal ImmutableRule string in models.ImmutableRule: %v", err), false
		}
		m.ImmutableRule = &immutableRuleValue
	}
	immutableRuleValueModel := m.ImmutableRule
	if swag.IsZero(immutableRuleValueModel) {
		immutableRuleValueModel = &models.ImmutableRule{}
	}
	err, added := retrieveModelImmutableRuleFlags(0, immutableRuleValueModel, "immutableRule", cmd)
	if err != nil {
		return err, false
	}
	if added {
		m.ImmutableRule = immutableRuleValueModel
	}
	if dryRun && debug {

		immutableRuleValueDebugBytes, err := json.Marshal(m.ImmutableRule)
		if err != nil {
			return err, false
		}
		logDebugf("ImmutableRule dry-run payload: %v", string(immutableRuleValueDebugBytes))
	}
	retAdded = retAdded || added

	return nil, retAdded
}
func retrieveOperationImmutableCreateImmuRuleXIsResourceNameFlag(m *immutable.CreateImmuRuleParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("X-Is-Resource-Name") {

		var xIsResourceNameFlagName string
		if cmdPrefix == "" {
			xIsResourceNameFlagName = "X-Is-Resource-Name"
		} else {
			xIsResourceNameFlagName = fmt.Sprintf("%v.X-Is-Resource-Name", cmdPrefix)
		}

		xIsResourceNameFlagValue, err := cmd.Flags().GetBool(xIsResourceNameFlagName)
		if err != nil {
			return err, false
		}
		m.XIsResourceName = &xIsResourceNameFlagValue

	}
	return nil, retAdded
}
func retrieveOperationImmutableCreateImmuRuleXRequestIDFlag(m *immutable.CreateImmuRuleParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("X-Request-Id") {

		var xRequestIdFlagName string
		if cmdPrefix == "" {
			xRequestIdFlagName = "X-Request-Id"
		} else {
			xRequestIdFlagName = fmt.Sprintf("%v.X-Request-Id", cmdPrefix)
		}

		xRequestIdFlagValue, err := cmd.Flags().GetString(xRequestIdFlagName)
		if err != nil {
			return err, false
		}
		m.XRequestID = &xRequestIdFlagValue

	}
	return nil, retAdded
}
func retrieveOperationImmutableCreateImmuRuleProjectNameOrIDFlag(m *immutable.CreateImmuRuleParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("project_name_or_id") {

		var projectNameOrIdFlagName string
		if cmdPrefix == "" {
			projectNameOrIdFlagName = "project_name_or_id"
		} else {
			projectNameOrIdFlagName = fmt.Sprintf("%v.project_name_or_id", cmdPrefix)
		}

		projectNameOrIdFlagValue, err := cmd.Flags().GetString(projectNameOrIdFlagName)
		if err != nil {
			return err, false
		}
		m.ProjectNameOrID = projectNameOrIdFlagValue

	}
	return nil, retAdded
}

// parseOperationImmutableCreateImmuRuleResult parses request result and return the string content
func parseOperationImmutableCreateImmuRuleResult(resp0 *immutable.CreateImmuRuleCreated, respErr error) (string, error) {
	if respErr != nil {

		// Non schema case: warning createImmuRuleCreated is not supported

		var iResp1 interface{} = respErr
		resp1, ok := iResp1.(*immutable.CreateImmuRuleBadRequest)
		if ok {
			if !swag.IsZero(resp1) && !swag.IsZero(resp1.Payload) {
				msgStr, err := json.Marshal(resp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp2 interface{} = respErr
		resp2, ok := iResp2.(*immutable.CreateImmuRuleUnauthorized)
		if ok {
			if !swag.IsZero(resp2) && !swag.IsZero(resp2.Payload) {
				msgStr, err := json.Marshal(resp2.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp3 interface{} = respErr
		resp3, ok := iResp3.(*immutable.CreateImmuRuleForbidden)
		if ok {
			if !swag.IsZero(resp3) && !swag.IsZero(resp3.Payload) {
				msgStr, err := json.Marshal(resp3.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp4 interface{} = respErr
		resp4, ok := iResp4.(*immutable.CreateImmuRuleNotFound)
		if ok {
			if !swag.IsZero(resp4) && !swag.IsZero(resp4.Payload) {
				msgStr, err := json.Marshal(resp4.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp5 interface{} = respErr
		resp5, ok := iResp5.(*immutable.CreateImmuRuleInternalServerError)
		if ok {
			if !swag.IsZero(resp5) && !swag.IsZero(resp5.Payload) {
				msgStr, err := json.Marshal(resp5.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	// warning: non schema response createImmuRuleCreated is not supported by go-swagger cli yet.

	return "", nil
}
