// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/laidbackware/harbor-cli/client/artifact"
	"github.com/laidbackware/harbor-cli/models"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationArtifactCreateTagCmd returns a cmd to handle operation createTag
func makeOperationArtifactCreateTagCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "createTag",
		Short: `Create a tag for the specified artifact`,
		RunE:  runOperationArtifactCreateTag,
	}

	if err := registerOperationArtifactCreateTagParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationArtifactCreateTag uses cmd flags to call endpoint api
func runOperationArtifactCreateTag(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := artifact.NewCreateTagParams()
	if err, _ := retrieveOperationArtifactCreateTagXRequestIDFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationArtifactCreateTagProjectNameFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationArtifactCreateTagReferenceFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationArtifactCreateTagRepositoryNameFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationArtifactCreateTagTagFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationArtifactCreateTagResult(appCli.Artifact.CreateTag(params, nil))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationArtifactCreateTagParamFlags registers all flags needed to fill params
func registerOperationArtifactCreateTagParamFlags(cmd *cobra.Command) error {
	if err := registerOperationArtifactCreateTagXRequestIDParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationArtifactCreateTagProjectNameParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationArtifactCreateTagReferenceParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationArtifactCreateTagRepositoryNameParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationArtifactCreateTagTagParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationArtifactCreateTagXRequestIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	xRequestIdDescription := `An unique ID for the request`

	var xRequestIdFlagName string
	if cmdPrefix == "" {
		xRequestIdFlagName = "X-Request-Id"
	} else {
		xRequestIdFlagName = fmt.Sprintf("%v.X-Request-Id", cmdPrefix)
	}

	var xRequestIdFlagDefault string

	_ = cmd.PersistentFlags().String(xRequestIdFlagName, xRequestIdFlagDefault, xRequestIdDescription)

	return nil
}
func registerOperationArtifactCreateTagProjectNameParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	projectNameDescription := `Required. The name of the project`

	var projectNameFlagName string
	if cmdPrefix == "" {
		projectNameFlagName = "project_name"
	} else {
		projectNameFlagName = fmt.Sprintf("%v.project_name", cmdPrefix)
	}

	var projectNameFlagDefault string

	_ = cmd.PersistentFlags().String(projectNameFlagName, projectNameFlagDefault, projectNameDescription)

	return nil
}
func registerOperationArtifactCreateTagReferenceParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	referenceDescription := `Required. The reference of the artifact, can be digest or tag`

	var referenceFlagName string
	if cmdPrefix == "" {
		referenceFlagName = "reference"
	} else {
		referenceFlagName = fmt.Sprintf("%v.reference", cmdPrefix)
	}

	var referenceFlagDefault string

	_ = cmd.PersistentFlags().String(referenceFlagName, referenceFlagDefault, referenceDescription)

	return nil
}
func registerOperationArtifactCreateTagRepositoryNameParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	repositoryNameDescription := `Required. The name of the repository. If it contains slash, encode it with URL encoding. e.g. a/b -> a%252Fb`

	var repositoryNameFlagName string
	if cmdPrefix == "" {
		repositoryNameFlagName = "repository_name"
	} else {
		repositoryNameFlagName = fmt.Sprintf("%v.repository_name", cmdPrefix)
	}

	var repositoryNameFlagDefault string

	_ = cmd.PersistentFlags().String(repositoryNameFlagName, repositoryNameFlagDefault, repositoryNameDescription)

	return nil
}
func registerOperationArtifactCreateTagTagParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	var tagFlagName string
	if cmdPrefix == "" {
		tagFlagName = "tag"
	} else {
		tagFlagName = fmt.Sprintf("%v.tag", cmdPrefix)
	}

	_ = cmd.PersistentFlags().String(tagFlagName, "", "Optional json string for [tag]. The JSON object of tag.")

	// add flags for body
	if err := registerModelTagFlags(0, "tag", cmd); err != nil {
		return err
	}

	return nil
}

func retrieveOperationArtifactCreateTagXRequestIDFlag(m *artifact.CreateTagParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("X-Request-Id") {

		var xRequestIdFlagName string
		if cmdPrefix == "" {
			xRequestIdFlagName = "X-Request-Id"
		} else {
			xRequestIdFlagName = fmt.Sprintf("%v.X-Request-Id", cmdPrefix)
		}

		xRequestIdFlagValue, err := cmd.Flags().GetString(xRequestIdFlagName)
		if err != nil {
			return err, false
		}
		m.XRequestID = &xRequestIdFlagValue

	}
	return nil, retAdded
}
func retrieveOperationArtifactCreateTagProjectNameFlag(m *artifact.CreateTagParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("project_name") {

		var projectNameFlagName string
		if cmdPrefix == "" {
			projectNameFlagName = "project_name"
		} else {
			projectNameFlagName = fmt.Sprintf("%v.project_name", cmdPrefix)
		}

		projectNameFlagValue, err := cmd.Flags().GetString(projectNameFlagName)
		if err != nil {
			return err, false
		}
		m.ProjectName = projectNameFlagValue

	}
	return nil, retAdded
}
func retrieveOperationArtifactCreateTagReferenceFlag(m *artifact.CreateTagParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("reference") {

		var referenceFlagName string
		if cmdPrefix == "" {
			referenceFlagName = "reference"
		} else {
			referenceFlagName = fmt.Sprintf("%v.reference", cmdPrefix)
		}

		referenceFlagValue, err := cmd.Flags().GetString(referenceFlagName)
		if err != nil {
			return err, false
		}
		m.Reference = referenceFlagValue

	}
	return nil, retAdded
}
func retrieveOperationArtifactCreateTagRepositoryNameFlag(m *artifact.CreateTagParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("repository_name") {

		var repositoryNameFlagName string
		if cmdPrefix == "" {
			repositoryNameFlagName = "repository_name"
		} else {
			repositoryNameFlagName = fmt.Sprintf("%v.repository_name", cmdPrefix)
		}

		repositoryNameFlagValue, err := cmd.Flags().GetString(repositoryNameFlagName)
		if err != nil {
			return err, false
		}
		m.RepositoryName = repositoryNameFlagValue

	}
	return nil, retAdded
}
func retrieveOperationArtifactCreateTagTagFlag(m *artifact.CreateTagParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("tag") {
		// Read tag string from cmd and unmarshal
		tagValueStr, err := cmd.Flags().GetString("tag")
		if err != nil {
			return err, false
		}

		tagValue := models.Tag{}
		if err := json.Unmarshal([]byte(tagValueStr), &tagValue); err != nil {
			return fmt.Errorf("cannot unmarshal tag string in models.Tag: %v", err), false
		}
		m.Tag = &tagValue
	}
	tagValueModel := m.Tag
	if swag.IsZero(tagValueModel) {
		tagValueModel = &models.Tag{}
	}
	err, added := retrieveModelTagFlags(0, tagValueModel, "tag", cmd)
	if err != nil {
		return err, false
	}
	if added {
		m.Tag = tagValueModel
	}
	if dryRun && debug {

		tagValueDebugBytes, err := json.Marshal(m.Tag)
		if err != nil {
			return err, false
		}
		logDebugf("Tag dry-run payload: %v", string(tagValueDebugBytes))
	}
	retAdded = retAdded || added

	return nil, retAdded
}

// parseOperationArtifactCreateTagResult parses request result and return the string content
func parseOperationArtifactCreateTagResult(resp0 *artifact.CreateTagCreated, respErr error) (string, error) {
	if respErr != nil {

		// Non schema case: warning createTagCreated is not supported

		var iResp1 interface{} = respErr
		resp1, ok := iResp1.(*artifact.CreateTagBadRequest)
		if ok {
			if !swag.IsZero(resp1) && !swag.IsZero(resp1.Payload) {
				msgStr, err := json.Marshal(resp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp2 interface{} = respErr
		resp2, ok := iResp2.(*artifact.CreateTagUnauthorized)
		if ok {
			if !swag.IsZero(resp2) && !swag.IsZero(resp2.Payload) {
				msgStr, err := json.Marshal(resp2.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp3 interface{} = respErr
		resp3, ok := iResp3.(*artifact.CreateTagForbidden)
		if ok {
			if !swag.IsZero(resp3) && !swag.IsZero(resp3.Payload) {
				msgStr, err := json.Marshal(resp3.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp4 interface{} = respErr
		resp4, ok := iResp4.(*artifact.CreateTagNotFound)
		if ok {
			if !swag.IsZero(resp4) && !swag.IsZero(resp4.Payload) {
				msgStr, err := json.Marshal(resp4.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp5 interface{} = respErr
		resp5, ok := iResp5.(*artifact.CreateTagMethodNotAllowed)
		if ok {
			if !swag.IsZero(resp5) && !swag.IsZero(resp5.Payload) {
				msgStr, err := json.Marshal(resp5.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp6 interface{} = respErr
		resp6, ok := iResp6.(*artifact.CreateTagConflict)
		if ok {
			if !swag.IsZero(resp6) && !swag.IsZero(resp6.Payload) {
				msgStr, err := json.Marshal(resp6.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp7 interface{} = respErr
		resp7, ok := iResp7.(*artifact.CreateTagInternalServerError)
		if ok {
			if !swag.IsZero(resp7) && !swag.IsZero(resp7.Payload) {
				msgStr, err := json.Marshal(resp7.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	// warning: non schema response createTagCreated is not supported by go-swagger cli yet.

	return "", nil
}
