// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/laidbackware/harbor-cli/client/artifact"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationArtifactDeleteTagCmd returns a cmd to handle operation deleteTag
func makeOperationArtifactDeleteTagCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "deleteTag",
		Short: `Delete the tag of the specified artifact`,
		RunE:  runOperationArtifactDeleteTag,
	}

	if err := registerOperationArtifactDeleteTagParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationArtifactDeleteTag uses cmd flags to call endpoint api
func runOperationArtifactDeleteTag(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := artifact.NewDeleteTagParams()
	if err, _ := retrieveOperationArtifactDeleteTagXRequestIDFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationArtifactDeleteTagProjectNameFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationArtifactDeleteTagReferenceFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationArtifactDeleteTagRepositoryNameFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationArtifactDeleteTagTagNameFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationArtifactDeleteTagResult(appCli.Artifact.DeleteTag(params, nil))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationArtifactDeleteTagParamFlags registers all flags needed to fill params
func registerOperationArtifactDeleteTagParamFlags(cmd *cobra.Command) error {
	if err := registerOperationArtifactDeleteTagXRequestIDParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationArtifactDeleteTagProjectNameParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationArtifactDeleteTagReferenceParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationArtifactDeleteTagRepositoryNameParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationArtifactDeleteTagTagNameParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationArtifactDeleteTagXRequestIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	xRequestIdDescription := `An unique ID for the request`

	var xRequestIdFlagName string
	if cmdPrefix == "" {
		xRequestIdFlagName = "X-Request-Id"
	} else {
		xRequestIdFlagName = fmt.Sprintf("%v.X-Request-Id", cmdPrefix)
	}

	var xRequestIdFlagDefault string

	_ = cmd.PersistentFlags().String(xRequestIdFlagName, xRequestIdFlagDefault, xRequestIdDescription)

	return nil
}
func registerOperationArtifactDeleteTagProjectNameParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	projectNameDescription := `Required. The name of the project`

	var projectNameFlagName string
	if cmdPrefix == "" {
		projectNameFlagName = "project_name"
	} else {
		projectNameFlagName = fmt.Sprintf("%v.project_name", cmdPrefix)
	}

	var projectNameFlagDefault string

	_ = cmd.PersistentFlags().String(projectNameFlagName, projectNameFlagDefault, projectNameDescription)

	return nil
}
func registerOperationArtifactDeleteTagReferenceParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	referenceDescription := `Required. The reference of the artifact, can be digest or tag`

	var referenceFlagName string
	if cmdPrefix == "" {
		referenceFlagName = "reference"
	} else {
		referenceFlagName = fmt.Sprintf("%v.reference", cmdPrefix)
	}

	var referenceFlagDefault string

	_ = cmd.PersistentFlags().String(referenceFlagName, referenceFlagDefault, referenceDescription)

	return nil
}
func registerOperationArtifactDeleteTagRepositoryNameParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	repositoryNameDescription := `Required. The name of the repository. If it contains slash, encode it with URL encoding. e.g. a/b -> a%252Fb`

	var repositoryNameFlagName string
	if cmdPrefix == "" {
		repositoryNameFlagName = "repository_name"
	} else {
		repositoryNameFlagName = fmt.Sprintf("%v.repository_name", cmdPrefix)
	}

	var repositoryNameFlagDefault string

	_ = cmd.PersistentFlags().String(repositoryNameFlagName, repositoryNameFlagDefault, repositoryNameDescription)

	return nil
}
func registerOperationArtifactDeleteTagTagNameParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	tagNameDescription := `Required. The name of the tag`

	var tagNameFlagName string
	if cmdPrefix == "" {
		tagNameFlagName = "tag_name"
	} else {
		tagNameFlagName = fmt.Sprintf("%v.tag_name", cmdPrefix)
	}

	var tagNameFlagDefault string

	_ = cmd.PersistentFlags().String(tagNameFlagName, tagNameFlagDefault, tagNameDescription)

	return nil
}

func retrieveOperationArtifactDeleteTagXRequestIDFlag(m *artifact.DeleteTagParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("X-Request-Id") {

		var xRequestIdFlagName string
		if cmdPrefix == "" {
			xRequestIdFlagName = "X-Request-Id"
		} else {
			xRequestIdFlagName = fmt.Sprintf("%v.X-Request-Id", cmdPrefix)
		}

		xRequestIdFlagValue, err := cmd.Flags().GetString(xRequestIdFlagName)
		if err != nil {
			return err, false
		}
		m.XRequestID = &xRequestIdFlagValue

	}
	return nil, retAdded
}
func retrieveOperationArtifactDeleteTagProjectNameFlag(m *artifact.DeleteTagParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("project_name") {

		var projectNameFlagName string
		if cmdPrefix == "" {
			projectNameFlagName = "project_name"
		} else {
			projectNameFlagName = fmt.Sprintf("%v.project_name", cmdPrefix)
		}

		projectNameFlagValue, err := cmd.Flags().GetString(projectNameFlagName)
		if err != nil {
			return err, false
		}
		m.ProjectName = projectNameFlagValue

	}
	return nil, retAdded
}
func retrieveOperationArtifactDeleteTagReferenceFlag(m *artifact.DeleteTagParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("reference") {

		var referenceFlagName string
		if cmdPrefix == "" {
			referenceFlagName = "reference"
		} else {
			referenceFlagName = fmt.Sprintf("%v.reference", cmdPrefix)
		}

		referenceFlagValue, err := cmd.Flags().GetString(referenceFlagName)
		if err != nil {
			return err, false
		}
		m.Reference = referenceFlagValue

	}
	return nil, retAdded
}
func retrieveOperationArtifactDeleteTagRepositoryNameFlag(m *artifact.DeleteTagParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("repository_name") {

		var repositoryNameFlagName string
		if cmdPrefix == "" {
			repositoryNameFlagName = "repository_name"
		} else {
			repositoryNameFlagName = fmt.Sprintf("%v.repository_name", cmdPrefix)
		}

		repositoryNameFlagValue, err := cmd.Flags().GetString(repositoryNameFlagName)
		if err != nil {
			return err, false
		}
		m.RepositoryName = repositoryNameFlagValue

	}
	return nil, retAdded
}
func retrieveOperationArtifactDeleteTagTagNameFlag(m *artifact.DeleteTagParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("tag_name") {

		var tagNameFlagName string
		if cmdPrefix == "" {
			tagNameFlagName = "tag_name"
		} else {
			tagNameFlagName = fmt.Sprintf("%v.tag_name", cmdPrefix)
		}

		tagNameFlagValue, err := cmd.Flags().GetString(tagNameFlagName)
		if err != nil {
			return err, false
		}
		m.TagName = tagNameFlagValue

	}
	return nil, retAdded
}

// parseOperationArtifactDeleteTagResult parses request result and return the string content
func parseOperationArtifactDeleteTagResult(resp0 *artifact.DeleteTagOK, respErr error) (string, error) {
	if respErr != nil {

		// Non schema case: warning deleteTagOK is not supported

		var iResp1 interface{} = respErr
		resp1, ok := iResp1.(*artifact.DeleteTagUnauthorized)
		if ok {
			if !swag.IsZero(resp1) && !swag.IsZero(resp1.Payload) {
				msgStr, err := json.Marshal(resp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp2 interface{} = respErr
		resp2, ok := iResp2.(*artifact.DeleteTagForbidden)
		if ok {
			if !swag.IsZero(resp2) && !swag.IsZero(resp2.Payload) {
				msgStr, err := json.Marshal(resp2.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp3 interface{} = respErr
		resp3, ok := iResp3.(*artifact.DeleteTagNotFound)
		if ok {
			if !swag.IsZero(resp3) && !swag.IsZero(resp3.Payload) {
				msgStr, err := json.Marshal(resp3.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp4 interface{} = respErr
		resp4, ok := iResp4.(*artifact.DeleteTagInternalServerError)
		if ok {
			if !swag.IsZero(resp4) && !swag.IsZero(resp4.Payload) {
				msgStr, err := json.Marshal(resp4.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	// warning: non schema response deleteTagOK is not supported by go-swagger cli yet.

	return "", nil
}
