// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/laidbackware/harbor-cli/client/configure"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationConfigureGetInternalconfigCmd returns a cmd to handle operation getInternalconfig
func makeOperationConfigureGetInternalconfigCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use: "getInternalconfig",
		Short: `This endpoint is for retrieving system configurations that only provides for internal api call.
`,
		RunE: runOperationConfigureGetInternalconfig,
	}

	if err := registerOperationConfigureGetInternalconfigParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationConfigureGetInternalconfig uses cmd flags to call endpoint api
func runOperationConfigureGetInternalconfig(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := configure.NewGetInternalconfigParams()
	if err, _ := retrieveOperationConfigureGetInternalconfigXRequestIDFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationConfigureGetInternalconfigResult(appCli.Configure.GetInternalconfig(params, nil))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationConfigureGetInternalconfigParamFlags registers all flags needed to fill params
func registerOperationConfigureGetInternalconfigParamFlags(cmd *cobra.Command) error {
	if err := registerOperationConfigureGetInternalconfigXRequestIDParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationConfigureGetInternalconfigXRequestIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	xRequestIdDescription := `An unique ID for the request`

	var xRequestIdFlagName string
	if cmdPrefix == "" {
		xRequestIdFlagName = "X-Request-Id"
	} else {
		xRequestIdFlagName = fmt.Sprintf("%v.X-Request-Id", cmdPrefix)
	}

	var xRequestIdFlagDefault string

	_ = cmd.PersistentFlags().String(xRequestIdFlagName, xRequestIdFlagDefault, xRequestIdDescription)

	return nil
}

func retrieveOperationConfigureGetInternalconfigXRequestIDFlag(m *configure.GetInternalconfigParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("X-Request-Id") {

		var xRequestIdFlagName string
		if cmdPrefix == "" {
			xRequestIdFlagName = "X-Request-Id"
		} else {
			xRequestIdFlagName = fmt.Sprintf("%v.X-Request-Id", cmdPrefix)
		}

		xRequestIdFlagValue, err := cmd.Flags().GetString(xRequestIdFlagName)
		if err != nil {
			return err, false
		}
		m.XRequestID = &xRequestIdFlagValue

	}
	return nil, retAdded
}

// parseOperationConfigureGetInternalconfigResult parses request result and return the string content
func parseOperationConfigureGetInternalconfigResult(resp0 *configure.GetInternalconfigOK, respErr error) (string, error) {
	if respErr != nil {

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*configure.GetInternalconfigOK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		// Non schema case: warning getInternalconfigUnauthorized is not supported

		// Non schema case: warning getInternalconfigForbidden is not supported

		// Non schema case: warning getInternalconfigInternalServerError is not supported

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}
