// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/laidbackware/harbor-cli/models"
	"github.com/spf13/cobra"
)

// Schema cli for LdapImportUsers

// register flags to command
func registerModelLdapImportUsersFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerLdapImportUsersLdapUIDList(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerLdapImportUsersLdapUIDList(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: ldap_uid_list []string array type is not supported by go-swagger cli yet

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelLdapImportUsersFlags(depth int, m *models.LdapImportUsers, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, ldapUidListAdded := retrieveLdapImportUsersLdapUIDListFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || ldapUidListAdded

	return nil, retAdded
}

func retrieveLdapImportUsersLdapUIDListFlags(depth int, m *models.LdapImportUsers, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	ldapUidListFlagName := fmt.Sprintf("%v.ldap_uid_list", cmdPrefix)
	if cmd.Flags().Changed(ldapUidListFlagName) {
		// warning: ldap_uid_list array type []string is not supported by go-swagger cli yet
	}

	return nil, retAdded
}
