// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/laidbackware/harbor-cli/client/retention"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationRetentionListRetentionExecutionsCmd returns a cmd to handle operation listRetentionExecutions
func makeOperationRetentionListRetentionExecutionsCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "listRetentionExecutions",
		Short: `Get Retention executions, execution status may be delayed before job service schedule it up.`,
		RunE:  runOperationRetentionListRetentionExecutions,
	}

	if err := registerOperationRetentionListRetentionExecutionsParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationRetentionListRetentionExecutions uses cmd flags to call endpoint api
func runOperationRetentionListRetentionExecutions(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := retention.NewListRetentionExecutionsParams()
	if err, _ := retrieveOperationRetentionListRetentionExecutionsXRequestIDFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationRetentionListRetentionExecutionsIDFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationRetentionListRetentionExecutionsPageFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationRetentionListRetentionExecutionsPageSizeFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationRetentionListRetentionExecutionsResult(appCli.Retention.ListRetentionExecutions(params, nil))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationRetentionListRetentionExecutionsParamFlags registers all flags needed to fill params
func registerOperationRetentionListRetentionExecutionsParamFlags(cmd *cobra.Command) error {
	if err := registerOperationRetentionListRetentionExecutionsXRequestIDParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationRetentionListRetentionExecutionsIDParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationRetentionListRetentionExecutionsPageParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationRetentionListRetentionExecutionsPageSizeParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationRetentionListRetentionExecutionsXRequestIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	xRequestIdDescription := `An unique ID for the request`

	var xRequestIdFlagName string
	if cmdPrefix == "" {
		xRequestIdFlagName = "X-Request-Id"
	} else {
		xRequestIdFlagName = fmt.Sprintf("%v.X-Request-Id", cmdPrefix)
	}

	var xRequestIdFlagDefault string

	_ = cmd.PersistentFlags().String(xRequestIdFlagName, xRequestIdFlagDefault, xRequestIdDescription)

	return nil
}
func registerOperationRetentionListRetentionExecutionsIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	idDescription := `Required. Retention ID.`

	var idFlagName string
	if cmdPrefix == "" {
		idFlagName = "id"
	} else {
		idFlagName = fmt.Sprintf("%v.id", cmdPrefix)
	}

	var idFlagDefault int64

	_ = cmd.PersistentFlags().Int64(idFlagName, idFlagDefault, idDescription)

	return nil
}
func registerOperationRetentionListRetentionExecutionsPageParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	pageDescription := `The page number.`

	var pageFlagName string
	if cmdPrefix == "" {
		pageFlagName = "page"
	} else {
		pageFlagName = fmt.Sprintf("%v.page", cmdPrefix)
	}

	var pageFlagDefault int64

	_ = cmd.PersistentFlags().Int64(pageFlagName, pageFlagDefault, pageDescription)

	return nil
}
func registerOperationRetentionListRetentionExecutionsPageSizeParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	pageSizeDescription := `The size of per page.`

	var pageSizeFlagName string
	if cmdPrefix == "" {
		pageSizeFlagName = "page_size"
	} else {
		pageSizeFlagName = fmt.Sprintf("%v.page_size", cmdPrefix)
	}

	var pageSizeFlagDefault int64

	_ = cmd.PersistentFlags().Int64(pageSizeFlagName, pageSizeFlagDefault, pageSizeDescription)

	return nil
}

func retrieveOperationRetentionListRetentionExecutionsXRequestIDFlag(m *retention.ListRetentionExecutionsParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("X-Request-Id") {

		var xRequestIdFlagName string
		if cmdPrefix == "" {
			xRequestIdFlagName = "X-Request-Id"
		} else {
			xRequestIdFlagName = fmt.Sprintf("%v.X-Request-Id", cmdPrefix)
		}

		xRequestIdFlagValue, err := cmd.Flags().GetString(xRequestIdFlagName)
		if err != nil {
			return err, false
		}
		m.XRequestID = &xRequestIdFlagValue

	}
	return nil, retAdded
}
func retrieveOperationRetentionListRetentionExecutionsIDFlag(m *retention.ListRetentionExecutionsParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("id") {

		var idFlagName string
		if cmdPrefix == "" {
			idFlagName = "id"
		} else {
			idFlagName = fmt.Sprintf("%v.id", cmdPrefix)
		}

		idFlagValue, err := cmd.Flags().GetInt64(idFlagName)
		if err != nil {
			return err, false
		}
		m.ID = idFlagValue

	}
	return nil, retAdded
}
func retrieveOperationRetentionListRetentionExecutionsPageFlag(m *retention.ListRetentionExecutionsParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("page") {

		var pageFlagName string
		if cmdPrefix == "" {
			pageFlagName = "page"
		} else {
			pageFlagName = fmt.Sprintf("%v.page", cmdPrefix)
		}

		pageFlagValue, err := cmd.Flags().GetInt64(pageFlagName)
		if err != nil {
			return err, false
		}
		m.Page = &pageFlagValue

	}
	return nil, retAdded
}
func retrieveOperationRetentionListRetentionExecutionsPageSizeFlag(m *retention.ListRetentionExecutionsParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("page_size") {

		var pageSizeFlagName string
		if cmdPrefix == "" {
			pageSizeFlagName = "page_size"
		} else {
			pageSizeFlagName = fmt.Sprintf("%v.page_size", cmdPrefix)
		}

		pageSizeFlagValue, err := cmd.Flags().GetInt64(pageSizeFlagName)
		if err != nil {
			return err, false
		}
		m.PageSize = &pageSizeFlagValue

	}
	return nil, retAdded
}

// parseOperationRetentionListRetentionExecutionsResult parses request result and return the string content
func parseOperationRetentionListRetentionExecutionsResult(resp0 *retention.ListRetentionExecutionsOK, respErr error) (string, error) {
	if respErr != nil {

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*retention.ListRetentionExecutionsOK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp1 interface{} = respErr
		resp1, ok := iResp1.(*retention.ListRetentionExecutionsUnauthorized)
		if ok {
			if !swag.IsZero(resp1) && !swag.IsZero(resp1.Payload) {
				msgStr, err := json.Marshal(resp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp2 interface{} = respErr
		resp2, ok := iResp2.(*retention.ListRetentionExecutionsForbidden)
		if ok {
			if !swag.IsZero(resp2) && !swag.IsZero(resp2.Payload) {
				msgStr, err := json.Marshal(resp2.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp3 interface{} = respErr
		resp3, ok := iResp3.(*retention.ListRetentionExecutionsInternalServerError)
		if ok {
			if !swag.IsZero(resp3) && !swag.IsZero(resp3.Payload) {
				msgStr, err := json.Marshal(resp3.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}
