// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/laidbackware/harbor-cli/client/project"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationProjectListProjectsCmd returns a cmd to handle operation listProjects
func makeOperationProjectListProjectsCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "listProjects",
		Short: `This endpoint returns projects created by Harbor.`,
		RunE:  runOperationProjectListProjects,
	}

	if err := registerOperationProjectListProjectsParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationProjectListProjects uses cmd flags to call endpoint api
func runOperationProjectListProjects(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := project.NewListProjectsParams()
	if err, _ := retrieveOperationProjectListProjectsXRequestIDFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationProjectListProjectsNameFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationProjectListProjectsOwnerFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationProjectListProjectsPageFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationProjectListProjectsPageSizeFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationProjectListProjectsPublicFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationProjectListProjectsQFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationProjectListProjectsSortFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationProjectListProjectsWithDetailFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationProjectListProjectsResult(appCli.Project.ListProjects(params, nil))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationProjectListProjectsParamFlags registers all flags needed to fill params
func registerOperationProjectListProjectsParamFlags(cmd *cobra.Command) error {
	if err := registerOperationProjectListProjectsXRequestIDParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationProjectListProjectsNameParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationProjectListProjectsOwnerParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationProjectListProjectsPageParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationProjectListProjectsPageSizeParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationProjectListProjectsPublicParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationProjectListProjectsQParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationProjectListProjectsSortParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationProjectListProjectsWithDetailParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationProjectListProjectsXRequestIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	xRequestIdDescription := `An unique ID for the request`

	var xRequestIdFlagName string
	if cmdPrefix == "" {
		xRequestIdFlagName = "X-Request-Id"
	} else {
		xRequestIdFlagName = fmt.Sprintf("%v.X-Request-Id", cmdPrefix)
	}

	var xRequestIdFlagDefault string

	_ = cmd.PersistentFlags().String(xRequestIdFlagName, xRequestIdFlagDefault, xRequestIdDescription)

	return nil
}
func registerOperationProjectListProjectsNameParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	nameDescription := `The name of project.`

	var nameFlagName string
	if cmdPrefix == "" {
		nameFlagName = "name"
	} else {
		nameFlagName = fmt.Sprintf("%v.name", cmdPrefix)
	}

	var nameFlagDefault string

	_ = cmd.PersistentFlags().String(nameFlagName, nameFlagDefault, nameDescription)

	return nil
}
func registerOperationProjectListProjectsOwnerParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	ownerDescription := `The name of project owner.`

	var ownerFlagName string
	if cmdPrefix == "" {
		ownerFlagName = "owner"
	} else {
		ownerFlagName = fmt.Sprintf("%v.owner", cmdPrefix)
	}

	var ownerFlagDefault string

	_ = cmd.PersistentFlags().String(ownerFlagName, ownerFlagDefault, ownerDescription)

	return nil
}
func registerOperationProjectListProjectsPageParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	pageDescription := `The page number`

	var pageFlagName string
	if cmdPrefix == "" {
		pageFlagName = "page"
	} else {
		pageFlagName = fmt.Sprintf("%v.page", cmdPrefix)
	}

	var pageFlagDefault int64 = 1

	_ = cmd.PersistentFlags().Int64(pageFlagName, pageFlagDefault, pageDescription)

	return nil
}
func registerOperationProjectListProjectsPageSizeParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	pageSizeDescription := `The size of per page`

	var pageSizeFlagName string
	if cmdPrefix == "" {
		pageSizeFlagName = "page_size"
	} else {
		pageSizeFlagName = fmt.Sprintf("%v.page_size", cmdPrefix)
	}

	var pageSizeFlagDefault int64 = 10

	_ = cmd.PersistentFlags().Int64(pageSizeFlagName, pageSizeFlagDefault, pageSizeDescription)

	return nil
}
func registerOperationProjectListProjectsPublicParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	publicDescription := `The project is public or private.`

	var publicFlagName string
	if cmdPrefix == "" {
		publicFlagName = "public"
	} else {
		publicFlagName = fmt.Sprintf("%v.public", cmdPrefix)
	}

	var publicFlagDefault bool

	_ = cmd.PersistentFlags().Bool(publicFlagName, publicFlagDefault, publicDescription)

	return nil
}
func registerOperationProjectListProjectsQParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	qDescription := `Query string to query resources. Supported query patterns are 'exact match(k=v)', 'fuzzy match(k=~v)', 'range(k=[min~max])', 'list with union releationship(k={v1 v2 v3})' and 'list with intersetion relationship(k=(v1 v2 v3))'. The value of range and list can be string(enclosed by ' or ), integer or time(in format '2020-04-09 02:36:00'). All of these query patterns should be put in the query string 'q=xxx' and splitted by ','. e.g. q=k1=v1,k2=~v2,k3=[min~max]`

	var qFlagName string
	if cmdPrefix == "" {
		qFlagName = "q"
	} else {
		qFlagName = fmt.Sprintf("%v.q", cmdPrefix)
	}

	var qFlagDefault string

	_ = cmd.PersistentFlags().String(qFlagName, qFlagDefault, qDescription)

	return nil
}
func registerOperationProjectListProjectsSortParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	sortDescription := `Sort the resource list in ascending or descending order. e.g. sort by field1 in ascending orderr and field2 in descending order with 'sort=field1,-field2'`

	var sortFlagName string
	if cmdPrefix == "" {
		sortFlagName = "sort"
	} else {
		sortFlagName = fmt.Sprintf("%v.sort", cmdPrefix)
	}

	var sortFlagDefault string

	_ = cmd.PersistentFlags().String(sortFlagName, sortFlagDefault, sortDescription)

	return nil
}
func registerOperationProjectListProjectsWithDetailParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	withDetailDescription := `Bool value indicating whether return detailed information of the project`

	var withDetailFlagName string
	if cmdPrefix == "" {
		withDetailFlagName = "with_detail"
	} else {
		withDetailFlagName = fmt.Sprintf("%v.with_detail", cmdPrefix)
	}

	var withDetailFlagDefault bool = true

	_ = cmd.PersistentFlags().Bool(withDetailFlagName, withDetailFlagDefault, withDetailDescription)

	return nil
}

func retrieveOperationProjectListProjectsXRequestIDFlag(m *project.ListProjectsParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("X-Request-Id") {

		var xRequestIdFlagName string
		if cmdPrefix == "" {
			xRequestIdFlagName = "X-Request-Id"
		} else {
			xRequestIdFlagName = fmt.Sprintf("%v.X-Request-Id", cmdPrefix)
		}

		xRequestIdFlagValue, err := cmd.Flags().GetString(xRequestIdFlagName)
		if err != nil {
			return err, false
		}
		m.XRequestID = &xRequestIdFlagValue

	}
	return nil, retAdded
}
func retrieveOperationProjectListProjectsNameFlag(m *project.ListProjectsParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("name") {

		var nameFlagName string
		if cmdPrefix == "" {
			nameFlagName = "name"
		} else {
			nameFlagName = fmt.Sprintf("%v.name", cmdPrefix)
		}

		nameFlagValue, err := cmd.Flags().GetString(nameFlagName)
		if err != nil {
			return err, false
		}
		m.Name = &nameFlagValue

	}
	return nil, retAdded
}
func retrieveOperationProjectListProjectsOwnerFlag(m *project.ListProjectsParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("owner") {

		var ownerFlagName string
		if cmdPrefix == "" {
			ownerFlagName = "owner"
		} else {
			ownerFlagName = fmt.Sprintf("%v.owner", cmdPrefix)
		}

		ownerFlagValue, err := cmd.Flags().GetString(ownerFlagName)
		if err != nil {
			return err, false
		}
		m.Owner = &ownerFlagValue

	}
	return nil, retAdded
}
func retrieveOperationProjectListProjectsPageFlag(m *project.ListProjectsParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("page") {

		var pageFlagName string
		if cmdPrefix == "" {
			pageFlagName = "page"
		} else {
			pageFlagName = fmt.Sprintf("%v.page", cmdPrefix)
		}

		pageFlagValue, err := cmd.Flags().GetInt64(pageFlagName)
		if err != nil {
			return err, false
		}
		m.Page = &pageFlagValue

	}
	return nil, retAdded
}
func retrieveOperationProjectListProjectsPageSizeFlag(m *project.ListProjectsParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("page_size") {

		var pageSizeFlagName string
		if cmdPrefix == "" {
			pageSizeFlagName = "page_size"
		} else {
			pageSizeFlagName = fmt.Sprintf("%v.page_size", cmdPrefix)
		}

		pageSizeFlagValue, err := cmd.Flags().GetInt64(pageSizeFlagName)
		if err != nil {
			return err, false
		}
		m.PageSize = &pageSizeFlagValue

	}
	return nil, retAdded
}
func retrieveOperationProjectListProjectsPublicFlag(m *project.ListProjectsParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("public") {

		var publicFlagName string
		if cmdPrefix == "" {
			publicFlagName = "public"
		} else {
			publicFlagName = fmt.Sprintf("%v.public", cmdPrefix)
		}

		publicFlagValue, err := cmd.Flags().GetBool(publicFlagName)
		if err != nil {
			return err, false
		}
		m.Public = &publicFlagValue

	}
	return nil, retAdded
}
func retrieveOperationProjectListProjectsQFlag(m *project.ListProjectsParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("q") {

		var qFlagName string
		if cmdPrefix == "" {
			qFlagName = "q"
		} else {
			qFlagName = fmt.Sprintf("%v.q", cmdPrefix)
		}

		qFlagValue, err := cmd.Flags().GetString(qFlagName)
		if err != nil {
			return err, false
		}
		m.Q = &qFlagValue

	}
	return nil, retAdded
}
func retrieveOperationProjectListProjectsSortFlag(m *project.ListProjectsParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("sort") {

		var sortFlagName string
		if cmdPrefix == "" {
			sortFlagName = "sort"
		} else {
			sortFlagName = fmt.Sprintf("%v.sort", cmdPrefix)
		}

		sortFlagValue, err := cmd.Flags().GetString(sortFlagName)
		if err != nil {
			return err, false
		}
		m.Sort = &sortFlagValue

	}
	return nil, retAdded
}
func retrieveOperationProjectListProjectsWithDetailFlag(m *project.ListProjectsParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("with_detail") {

		var withDetailFlagName string
		if cmdPrefix == "" {
			withDetailFlagName = "with_detail"
		} else {
			withDetailFlagName = fmt.Sprintf("%v.with_detail", cmdPrefix)
		}

		withDetailFlagValue, err := cmd.Flags().GetBool(withDetailFlagName)
		if err != nil {
			return err, false
		}
		m.WithDetail = &withDetailFlagValue

	}
	return nil, retAdded
}

// parseOperationProjectListProjectsResult parses request result and return the string content
func parseOperationProjectListProjectsResult(resp0 *project.ListProjectsOK, respErr error) (string, error) {
	if respErr != nil {

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*project.ListProjectsOK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp1 interface{} = respErr
		resp1, ok := iResp1.(*project.ListProjectsUnauthorized)
		if ok {
			if !swag.IsZero(resp1) && !swag.IsZero(resp1.Payload) {
				msgStr, err := json.Marshal(resp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp2 interface{} = respErr
		resp2, ok := iResp2.(*project.ListProjectsInternalServerError)
		if ok {
			if !swag.IsZero(resp2) && !swag.IsZero(resp2.Payload) {
				msgStr, err := json.Marshal(resp2.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}
