// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/laidbackware/harbor-cli/models"
	"github.com/spf13/cobra"
)

// Schema cli for SupportedWebhookEventTypes

// register flags to command
func registerModelSupportedWebhookEventTypesFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerSupportedWebhookEventTypesEventType(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerSupportedWebhookEventTypesNotifyType(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerSupportedWebhookEventTypesEventType(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: event_type []EventType array type is not supported by go-swagger cli yet

	return nil
}

func registerSupportedWebhookEventTypesNotifyType(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: notify_type []NotifyType array type is not supported by go-swagger cli yet

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelSupportedWebhookEventTypesFlags(depth int, m *models.SupportedWebhookEventTypes, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, eventTypeAdded := retrieveSupportedWebhookEventTypesEventTypeFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || eventTypeAdded

	err, notifyTypeAdded := retrieveSupportedWebhookEventTypesNotifyTypeFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || notifyTypeAdded

	return nil, retAdded
}

func retrieveSupportedWebhookEventTypesEventTypeFlags(depth int, m *models.SupportedWebhookEventTypes, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	eventTypeFlagName := fmt.Sprintf("%v.event_type", cmdPrefix)
	if cmd.Flags().Changed(eventTypeFlagName) {
		// warning: event_type array type []EventType is not supported by go-swagger cli yet
	}

	return nil, retAdded
}

func retrieveSupportedWebhookEventTypesNotifyTypeFlags(depth int, m *models.SupportedWebhookEventTypes, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	notifyTypeFlagName := fmt.Sprintf("%v.notify_type", cmdPrefix)
	if cmd.Flags().Changed(notifyTypeFlagName) {
		// warning: notify_type array type []NotifyType is not supported by go-swagger cli yet
	}

	return nil, retAdded
}
