// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/laidbackware/harbor-cli/client/quota"
	"github.com/laidbackware/harbor-cli/models"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationQuotaUpdateQuotaCmd returns a cmd to handle operation updateQuota
func makeOperationQuotaUpdateQuotaCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "updateQuota",
		Short: `Update hard limits of the specified quota`,
		RunE:  runOperationQuotaUpdateQuota,
	}

	if err := registerOperationQuotaUpdateQuotaParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationQuotaUpdateQuota uses cmd flags to call endpoint api
func runOperationQuotaUpdateQuota(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := quota.NewUpdateQuotaParams()
	if err, _ := retrieveOperationQuotaUpdateQuotaXRequestIDFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationQuotaUpdateQuotaHardFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationQuotaUpdateQuotaIDFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationQuotaUpdateQuotaResult(appCli.Quota.UpdateQuota(params, nil))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationQuotaUpdateQuotaParamFlags registers all flags needed to fill params
func registerOperationQuotaUpdateQuotaParamFlags(cmd *cobra.Command) error {
	if err := registerOperationQuotaUpdateQuotaXRequestIDParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationQuotaUpdateQuotaHardParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationQuotaUpdateQuotaIDParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationQuotaUpdateQuotaXRequestIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	xRequestIdDescription := `An unique ID for the request`

	var xRequestIdFlagName string
	if cmdPrefix == "" {
		xRequestIdFlagName = "X-Request-Id"
	} else {
		xRequestIdFlagName = fmt.Sprintf("%v.X-Request-Id", cmdPrefix)
	}

	var xRequestIdFlagDefault string

	_ = cmd.PersistentFlags().String(xRequestIdFlagName, xRequestIdFlagDefault, xRequestIdDescription)

	return nil
}
func registerOperationQuotaUpdateQuotaHardParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	var hardFlagName string
	if cmdPrefix == "" {
		hardFlagName = "hard"
	} else {
		hardFlagName = fmt.Sprintf("%v.hard", cmdPrefix)
	}

	_ = cmd.PersistentFlags().String(hardFlagName, "", "Optional json string for [hard]. The new hard limits for the quota")

	// add flags for body
	if err := registerModelQuotaUpdateReqFlags(0, "quotaUpdateReq", cmd); err != nil {
		return err
	}

	return nil
}
func registerOperationQuotaUpdateQuotaIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	idDescription := `Required. Quota ID`

	var idFlagName string
	if cmdPrefix == "" {
		idFlagName = "id"
	} else {
		idFlagName = fmt.Sprintf("%v.id", cmdPrefix)
	}

	var idFlagDefault int64

	_ = cmd.PersistentFlags().Int64(idFlagName, idFlagDefault, idDescription)

	return nil
}

func retrieveOperationQuotaUpdateQuotaXRequestIDFlag(m *quota.UpdateQuotaParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("X-Request-Id") {

		var xRequestIdFlagName string
		if cmdPrefix == "" {
			xRequestIdFlagName = "X-Request-Id"
		} else {
			xRequestIdFlagName = fmt.Sprintf("%v.X-Request-Id", cmdPrefix)
		}

		xRequestIdFlagValue, err := cmd.Flags().GetString(xRequestIdFlagName)
		if err != nil {
			return err, false
		}
		m.XRequestID = &xRequestIdFlagValue

	}
	return nil, retAdded
}
func retrieveOperationQuotaUpdateQuotaHardFlag(m *quota.UpdateQuotaParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("hard") {
		// Read hard string from cmd and unmarshal
		hardValueStr, err := cmd.Flags().GetString("hard")
		if err != nil {
			return err, false
		}

		hardValue := models.QuotaUpdateReq{}
		if err := json.Unmarshal([]byte(hardValueStr), &hardValue); err != nil {
			return fmt.Errorf("cannot unmarshal hard string in models.QuotaUpdateReq: %v", err), false
		}
		m.Hard = &hardValue
	}
	hardValueModel := m.Hard
	if swag.IsZero(hardValueModel) {
		hardValueModel = &models.QuotaUpdateReq{}
	}
	err, added := retrieveModelQuotaUpdateReqFlags(0, hardValueModel, "quotaUpdateReq", cmd)
	if err != nil {
		return err, false
	}
	if added {
		m.Hard = hardValueModel
	}
	if dryRun && debug {

		hardValueDebugBytes, err := json.Marshal(m.Hard)
		if err != nil {
			return err, false
		}
		logDebugf("Hard dry-run payload: %v", string(hardValueDebugBytes))
	}
	retAdded = retAdded || added

	return nil, retAdded
}
func retrieveOperationQuotaUpdateQuotaIDFlag(m *quota.UpdateQuotaParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("id") {

		var idFlagName string
		if cmdPrefix == "" {
			idFlagName = "id"
		} else {
			idFlagName = fmt.Sprintf("%v.id", cmdPrefix)
		}

		idFlagValue, err := cmd.Flags().GetInt64(idFlagName)
		if err != nil {
			return err, false
		}
		m.ID = idFlagValue

	}
	return nil, retAdded
}

// parseOperationQuotaUpdateQuotaResult parses request result and return the string content
func parseOperationQuotaUpdateQuotaResult(resp0 *quota.UpdateQuotaOK, respErr error) (string, error) {
	if respErr != nil {

		// Non schema case: warning updateQuotaOK is not supported

		var iResp1 interface{} = respErr
		resp1, ok := iResp1.(*quota.UpdateQuotaBadRequest)
		if ok {
			if !swag.IsZero(resp1) && !swag.IsZero(resp1.Payload) {
				msgStr, err := json.Marshal(resp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp2 interface{} = respErr
		resp2, ok := iResp2.(*quota.UpdateQuotaUnauthorized)
		if ok {
			if !swag.IsZero(resp2) && !swag.IsZero(resp2.Payload) {
				msgStr, err := json.Marshal(resp2.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp3 interface{} = respErr
		resp3, ok := iResp3.(*quota.UpdateQuotaForbidden)
		if ok {
			if !swag.IsZero(resp3) && !swag.IsZero(resp3.Payload) {
				msgStr, err := json.Marshal(resp3.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp4 interface{} = respErr
		resp4, ok := iResp4.(*quota.UpdateQuotaNotFound)
		if ok {
			if !swag.IsZero(resp4) && !swag.IsZero(resp4.Payload) {
				msgStr, err := json.Marshal(resp4.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp5 interface{} = respErr
		resp5, ok := iResp5.(*quota.UpdateQuotaInternalServerError)
		if ok {
			if !swag.IsZero(resp5) && !swag.IsZero(resp5.Payload) {
				msgStr, err := json.Marshal(resp5.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	// warning: non schema response updateQuotaOK is not supported by go-swagger cli yet.

	return "", nil
}
