// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/laidbackware/harbor-cli/client/label"
	"github.com/laidbackware/harbor-cli/models"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationLabelUpdateLabelCmd returns a cmd to handle operation updateLabel
func makeOperationLabelUpdateLabelCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use: "UpdateLabel",
		Short: `This endpoint let user update label properties.
`,
		RunE: runOperationLabelUpdateLabel,
	}

	if err := registerOperationLabelUpdateLabelParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationLabelUpdateLabel uses cmd flags to call endpoint api
func runOperationLabelUpdateLabel(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := label.NewUpdateLabelParams()
	if err, _ := retrieveOperationLabelUpdateLabelXRequestIDFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationLabelUpdateLabelLabelFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationLabelUpdateLabelLabelIDFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationLabelUpdateLabelResult(appCli.Label.UpdateLabel(params, nil))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationLabelUpdateLabelParamFlags registers all flags needed to fill params
func registerOperationLabelUpdateLabelParamFlags(cmd *cobra.Command) error {
	if err := registerOperationLabelUpdateLabelXRequestIDParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationLabelUpdateLabelLabelParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationLabelUpdateLabelLabelIDParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationLabelUpdateLabelXRequestIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	xRequestIdDescription := `An unique ID for the request`

	var xRequestIdFlagName string
	if cmdPrefix == "" {
		xRequestIdFlagName = "X-Request-Id"
	} else {
		xRequestIdFlagName = fmt.Sprintf("%v.X-Request-Id", cmdPrefix)
	}

	var xRequestIdFlagDefault string

	_ = cmd.PersistentFlags().String(xRequestIdFlagName, xRequestIdFlagDefault, xRequestIdDescription)

	return nil
}
func registerOperationLabelUpdateLabelLabelParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	var labelFlagName string
	if cmdPrefix == "" {
		labelFlagName = "label"
	} else {
		labelFlagName = fmt.Sprintf("%v.label", cmdPrefix)
	}

	_ = cmd.PersistentFlags().String(labelFlagName, "", "Optional json string for [label]. The updated label json object.")

	// add flags for body
	if err := registerModelLabelFlags(0, "label", cmd); err != nil {
		return err
	}

	return nil
}
func registerOperationLabelUpdateLabelLabelIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	labelIdDescription := `Required. Label ID`

	var labelIdFlagName string
	if cmdPrefix == "" {
		labelIdFlagName = "label_id"
	} else {
		labelIdFlagName = fmt.Sprintf("%v.label_id", cmdPrefix)
	}

	var labelIdFlagDefault int64

	_ = cmd.PersistentFlags().Int64(labelIdFlagName, labelIdFlagDefault, labelIdDescription)

	return nil
}

func retrieveOperationLabelUpdateLabelXRequestIDFlag(m *label.UpdateLabelParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("X-Request-Id") {

		var xRequestIdFlagName string
		if cmdPrefix == "" {
			xRequestIdFlagName = "X-Request-Id"
		} else {
			xRequestIdFlagName = fmt.Sprintf("%v.X-Request-Id", cmdPrefix)
		}

		xRequestIdFlagValue, err := cmd.Flags().GetString(xRequestIdFlagName)
		if err != nil {
			return err, false
		}
		m.XRequestID = &xRequestIdFlagValue

	}
	return nil, retAdded
}
func retrieveOperationLabelUpdateLabelLabelFlag(m *label.UpdateLabelParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("label") {
		// Read label string from cmd and unmarshal
		labelValueStr, err := cmd.Flags().GetString("label")
		if err != nil {
			return err, false
		}

		labelValue := models.Label{}
		if err := json.Unmarshal([]byte(labelValueStr), &labelValue); err != nil {
			return fmt.Errorf("cannot unmarshal label string in models.Label: %v", err), false
		}
		m.Label = &labelValue
	}
	labelValueModel := m.Label
	if swag.IsZero(labelValueModel) {
		labelValueModel = &models.Label{}
	}
	err, added := retrieveModelLabelFlags(0, labelValueModel, "label", cmd)
	if err != nil {
		return err, false
	}
	if added {
		m.Label = labelValueModel
	}
	if dryRun && debug {

		labelValueDebugBytes, err := json.Marshal(m.Label)
		if err != nil {
			return err, false
		}
		logDebugf("Label dry-run payload: %v", string(labelValueDebugBytes))
	}
	retAdded = retAdded || added

	return nil, retAdded
}
func retrieveOperationLabelUpdateLabelLabelIDFlag(m *label.UpdateLabelParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("label_id") {

		var labelIdFlagName string
		if cmdPrefix == "" {
			labelIdFlagName = "label_id"
		} else {
			labelIdFlagName = fmt.Sprintf("%v.label_id", cmdPrefix)
		}

		labelIdFlagValue, err := cmd.Flags().GetInt64(labelIdFlagName)
		if err != nil {
			return err, false
		}
		m.LabelID = labelIdFlagValue

	}
	return nil, retAdded
}

// parseOperationLabelUpdateLabelResult parses request result and return the string content
func parseOperationLabelUpdateLabelResult(resp0 *label.UpdateLabelOK, respErr error) (string, error) {
	if respErr != nil {

		// Non schema case: warning updateLabelOK is not supported

		var iResp1 interface{} = respErr
		resp1, ok := iResp1.(*label.UpdateLabelBadRequest)
		if ok {
			if !swag.IsZero(resp1) && !swag.IsZero(resp1.Payload) {
				msgStr, err := json.Marshal(resp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp2 interface{} = respErr
		resp2, ok := iResp2.(*label.UpdateLabelUnauthorized)
		if ok {
			if !swag.IsZero(resp2) && !swag.IsZero(resp2.Payload) {
				msgStr, err := json.Marshal(resp2.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp3 interface{} = respErr
		resp3, ok := iResp3.(*label.UpdateLabelNotFound)
		if ok {
			if !swag.IsZero(resp3) && !swag.IsZero(resp3.Payload) {
				msgStr, err := json.Marshal(resp3.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp4 interface{} = respErr
		resp4, ok := iResp4.(*label.UpdateLabelConflict)
		if ok {
			if !swag.IsZero(resp4) && !swag.IsZero(resp4.Payload) {
				msgStr, err := json.Marshal(resp4.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp5 interface{} = respErr
		resp5, ok := iResp5.(*label.UpdateLabelInternalServerError)
		if ok {
			if !swag.IsZero(resp5) && !swag.IsZero(resp5.Payload) {
				msgStr, err := json.Marshal(resp5.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	// warning: non schema response updateLabelOK is not supported by go-swagger cli yet.

	return "", nil
}
